export const categorias = ["Juegos", "Consolas", "Pc"];
export const informacion = [
  [
    "Juegos",
    "assets/img/juegos/asa.jpg",
    "Assasin's Creed",
    "119.000",
    "Assassins Creed es un videojuego de aventura de acción y de sigilo en la que el jugador sobre todo asume el papel de Altaïr, experimentado por el protagonista Desmond Miles. El objetivo principal del juego es llevar a cabo una serie de asesinatos ordenados por Al Mualim, el líder de los asesinos",
  ],
  [
    "Juegos",
    "assets/img/juegos/BO3.jpg",
    "COD Black Ops 3",
    "130.000",
    "Call of Duty: Black Ops III tiene lugar en un futuro distópico, situado en 2065, donde la ciencia y la tecnología han cambiado radicalmente a la especie humana, con una sociedad violenta y multitud de protestas tratando de detener el progreso de la tecnología.",
  ],
  [
    "Juegos",
    "assets/img/juegos/God.jpg",
    "God of war",
    "150.000",
    "El videojuego se centra en la historia de la mitología nórdica, a diferencia de los títulos anteriores, que se ubicaban en la Antigua Grecia y su mitología. Con el cambio de cultura, hacen su aparición espacios míticos como el árbol de Yggdrasil y criaturas como la serpiente Jörmungandr",
  ],
  [
    "Juegos",
    "assets/img/juegos/left.jpg",
    "Left 4 dead",
    "98.000",
    "Left 4 Dead es un videojuego de disparos en primera persona, cooperativo y asimétrico del género «videojuego de terror», desarrollado por Turtle Rock Studios y publicado por Valve Corporation.",
  ],
  [
    "Juegos",
    "assets/img/juegos/mortal.jpg",
    "Mortal combat x",
    "100.000",
    "Mortal Kombat X es la décima entrega de la serie de lucha Mortal Kombat de NetherRealm Studios, un juego ue ofrece una nueva experiencia conectada que permite a los jugadores participar en una competición online donde cada lucha será fundamental en una batalla global por la supremacía.",
  ],
  [
    "Juegos",
    "assets/img/juegos/Street.webp",
    "Street Fighter V",
    "125.000",
    "¡Experimenta la intensidad de la batalla cara a cara en Street Fighter® V! Elige entre 16 personajes icónicos, cada uno con su propia historia personal y desafíos de entrenamiento únicos, y luego lucha contra amigos en línea o sin conexión con una sólida variedad de opciones para cada partida.",
  ],
  [
    "Consolas",
    "assets/img/consolas/xbox-control.png",
    "Control xbox one",
    "300.000",
    "Experimenta el diseño modernizado del Control inalámbrico Xbox, con superficies esculpidas y una geometría refinada para disfrutar de una mayor comodidad durante el juego. Mantén el objetivo con el agarre texturizado y control de dirección híbrido.",
  ],
  [
    "Consolas",
    "assets/img/consolas/ps5.png",
    "Play 5",
    "3.000.000",
    "Experimenta una velocidad sorprendente con una SSD de velocidad ultrarrápida, una inmersión más profunda con soporte para respuesta háptica1, gatillos adaptables1 y audio 3D*, además de una generación completamente nueva de juegos de PlayStation.",
  ],
  [
    "Consolas",
    "assets/img/consolas/console.png",
    "Nintendo Nes",
    "80.000",
    "o que comenzó como Famicom (Family Computer) en Japón, fue Nintendo Entertainment System en occidente, que desafió a los expertos y se vendió por millones. Los jugadores se apresuraron en ver y jugar a clásicos como Super Mario Bros., The Legend of Zelda y Excitebike, juegos que estaban muy por encima de los juegos para otras consolas domésticas.",
  ],
  [
    "Consolas",
    "assets/img/consolas/switch.png",
    "Nintendo switch",
    "1.000.000",
    "La consola Nintendo Switch está diseñada para cualquier estilo de vida, transformándose rápidamente de una consola casera a una consola portátil.",
  ],
  [
    "Consolas",
    "assets/img/consolas/xboxone.png",
    "Xbox Series X",
    "2.300.000",
    "Los 12 teraflops de potencia de procesamiento alojados en el sistema en un chip (SOC) funcionan con las arquitecturas Zen 2 y RDNA 2 de AMD para crear mundos que te dejarán embelesado.",
  ],
  [
    "Consolas",
    "assets/img/consolas/atari.png",
    "Atari",
    "50.000",
    "Palabras como retro o clásico se han utilizado tanto, que en parte han perdido su significado. Muchos gamers utilizan el término videojuego clásico cuando quieren decir antiguo, porque un juego mediocre de clásico tiene poco. O llaman consola retro a una máquina que apenas tiene 10 o 15 años.",
  ],
  [
    "Pc",
    "assets/img/pc/pc1.jpg",
    "Pc Gamer Torre Power",
    "3.179.900",
    "PROCESADOR AMD RYZEN 5 3400G RELOJ DE AUMENTO MAX: 4.2GHzN.º DE NUCLEOS DE CPU: 4 N.º DE SUBPROCESOS 8.TARJETA DE VIDEO : VEGA 11 DE 2GB INTEGRADA .",
  ],
  ["Pc", "assets/img/pc/pc2.jpg", "Pc Gamer Amd Ryzen", "3.339.900","PC EQUIPO GAMER AMD RYZEN 5 5600G CON B450M SOLIDO 256GB RAM 16GB 3200 MHZ RGB.CARACTERÍSTICAS PRINCIPALES¡NUEVA GENERACION DE PROCESDORE AMD!"],
  ["Pc", "assets/img/pc/pc3.jpg", "PC Gamer Complet", "3.150.900","PC Gamer Complet, Ordenadores de Escritorio, PC Gamer Fixe, Procesador AMD A10 9700 de 4 núcleos, Pantalla LED de 22', Teclado y Ratón Gamer, 16 GB, 1 TB, Funda CiT Seven RGB, WiFi, Windows 10"],
  ["Pc", "assets/img/pc/pc4.jpg", "PC Gamer Draco", "4.000.000","CPU Intel Core i7 10700F2.90 GHz, 12 MB Caché L3 Disco Sólido M2 500GB NVME Memoria RAM 16GB DDR4 Monitor LED 24″ FHD Curvo Mainboard B460M Tarjeta de Video  GTX1660 super 6gb DVI/HDMI/Display Port Teclado Mecánico, mouse Cooler Gammax Fuente Certificada 700W"],
  ["Pc", "assets/img/pc/pc5.jpg", "PC Gamer Draco", "4.500.000","CPU Intel Core i7 10700F 2.90 GHz, 12 MB Caché L3 Disco Sólido M2 1TB NVME Memoria RAM 32GB DDR4 Monitor LED 24' FHD Curvo Mainboard B460 Tarjeta de Video  GTX1660 super 6gb DVI/HDMI/Display Port/ Wifi/ Camara FHD Teclado Mecánico, mouse/ Auricular Ludico Cooler Gammax Fuente Certificada 700W  "],
  ["Pc", "assets/img/pc/pc6.jpg", "PC Gamer Intel", "3.800.000","PROCESADOR INTEL® CORE™ i7-11700 (HASTA 4.90 GHZ) CANTIDAD DE NÚCLEOS 8 CANTIDAD DE SUBPROCESOS 16 FRECUENCIA BASICA DEL PROCESADOR: 2,50 GHZ. FRECUENCIA TURBO MAXIMA: 4,90 GHz TARJETA DE VIDEO : NVIDIA GEFORCE GT 1030 2GB MEMORIA RAM: PC DDR4 16GB RGB (2X8) 3200MHZ TIPO DE PLACA O BOARD: ASUS PRIME H410M-E LGA1200 DISCO DURO SOLIDO: SSD 480GB CONEXION SATA. DISCO DURO MECANICO: HDD 1TB.CAJA & CHASIS: MEDIA ATX METALICO (INCLUYE 1 VENTILADOT DE LUZ). FUENTE DE PODER: 450WA REALES. MONITOR INCLUIDO: 22 PULGADAS FULL HD (1920px X 1080px) CON HDMI & VGA."],
];
